/*
 * Sauce Labs REST API
 *
 * This is a REST API documentation provided by Sauce Labs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@saucelabs.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommandCountStats {
    #[serde(rename = "all", skip_serializing_if = "Option::is_none")]
    pub all: Option<i32>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<i32>,
}

impl CommandCountStats {
    pub fn new() -> CommandCountStats {
        CommandCountStats {
            all: None,
            error: None,
        }
    }
}


