/*
 * Sauce Labs REST API
 *
 * This is a REST API documentation provided by Sauce Labs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@saucelabs.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2006 {
    #[serde(rename = "automated", skip_serializing_if = "Option::is_none")]
    pub automated: Option<String>,
    #[serde(rename = "manual", skip_serializing_if = "Option::is_none")]
    pub manual: Option<String>,
}

impl InlineResponse2006 {
    pub fn new() -> InlineResponse2006 {
        InlineResponse2006 {
            automated: None,
            manual: None,
        }
    }
}


