/*
 * Sauce Labs REST API
 *
 * This is a REST API documentation provided by Sauce Labs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@saucelabs.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2005 {
    #[serde(rename = "exp", skip_serializing_if = "Option::is_none")]
    pub exp: Option<i32>,
    #[serde(rename = "iat", skip_serializing_if = "Option::is_none")]
    pub iat: Option<i32>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

impl InlineResponse2005 {
    pub fn new() -> InlineResponse2005 {
        InlineResponse2005 {
            exp: None,
            iat: None,
            username: None,
        }
    }
}


