/*
 * Sauce Labs REST API
 *
 * This is a REST API documentation provided by Sauce Labs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@saucelabs.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SauceStatus {
    #[serde(rename = "service_operational", skip_serializing_if = "Option::is_none")]
    pub service_operational: Option<bool>,
    #[serde(rename = "status_message", skip_serializing_if = "Option::is_none")]
    pub status_message: Option<String>,
    #[serde(rename = "wait_time", skip_serializing_if = "Option::is_none")]
    pub wait_time: Option<f64>,
}

impl SauceStatus {
    pub fn new() -> SauceStatus {
        SauceStatus {
            service_operational: None,
            status_message: None,
            wait_time: None,
        }
    }
}


