/*
 * Sauce Labs REST API
 *
 * This is a REST API documentation provided by Sauce Labs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@saucelabs.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TunnelMetaData {
    #[serde(rename = "build", skip_serializing_if = "Option::is_none")]
    pub build: Option<String>,
    #[serde(rename = "command", skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
    #[serde(rename = "git_version", skip_serializing_if = "Option::is_none")]
    pub git_version: Option<String>,
    #[serde(rename = "hostname", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
    #[serde(rename = "nofile_limit", skip_serializing_if = "Option::is_none")]
    pub nofile_limit: Option<i32>,
    #[serde(rename = "platform", skip_serializing_if = "Option::is_none")]
    pub platform: Option<String>,
    #[serde(rename = "release", skip_serializing_if = "Option::is_none")]
    pub release: Option<String>,
}

impl TunnelMetaData {
    pub fn new() -> TunnelMetaData {
        TunnelMetaData {
            build: None,
            command: None,
            git_version: None,
            hostname: None,
            nofile_limit: None,
            platform: None,
            release: None,
        }
    }
}


