/*
 * Sauce Labs REST API
 *
 * This is a REST API documentation provided by Sauce Labs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@saucelabs.com
 * Generated by: https://openapi-generator.tech
 */

/// WhoamiUser : User



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WhoamiUser {
    #[serde(rename = "access_key", skip_serializing_if = "Option::is_none")]
    pub access_key: Option<String>,
    #[serde(rename = "ancestor_concurrency_limit", skip_serializing_if = "Option::is_none")]
    pub ancestor_concurrency_limit: Option<Box<crate::models::ConcurrencyLimit>>,
    #[serde(rename = "can_run_manual", skip_serializing_if = "Option::is_none")]
    pub can_run_manual: Option<bool>,
    #[serde(rename = "concurrency_limit", skip_serializing_if = "Option::is_none")]
    pub concurrency_limit: Option<Box<crate::models::ConcurrencyLimit>>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "first_name", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "last_name", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    #[serde(rename = "manual_minutes", skip_serializing_if = "Option::is_none")]
    pub manual_minutes: Option<i32>,
    #[serde(rename = "minutes", skip_serializing_if = "Option::is_none")]
    pub minutes: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "subscribed", skip_serializing_if = "Option::is_none")]
    pub subscribed: Option<bool>,
    #[serde(rename = "user_type", skip_serializing_if = "Option::is_none")]
    pub user_type: Option<String>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "verified", skip_serializing_if = "Option::is_none")]
    pub verified: Option<bool>,
}

impl WhoamiUser {
    /// User
    pub fn new() -> WhoamiUser {
        WhoamiUser {
            access_key: None,
            ancestor_concurrency_limit: None,
            can_run_manual: None,
            concurrency_limit: None,
            email: None,
            first_name: None,
            id: None,
            last_name: None,
            manual_minutes: None,
            minutes: None,
            name: None,
            subscribed: None,
            user_type: None,
            username: None,
            verified: None,
        }
    }
}


