/*
 * Sauce Labs REST API
 *
 * This is a REST API documentation provided by Sauce Labs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@saucelabs.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Activity {
    #[serde(rename = "ccy_exec_peak")]
    pub ccy_exec_peak: Vec<i32>,
    #[serde(rename = "datestamp")]
    pub datestamp: Vec<String>,
    #[serde(rename = "jobs")]
    pub jobs: Vec<i32>,
    #[serde(rename = "minutes")]
    pub minutes: Vec<i32>,
}

impl Activity {
    pub fn new(ccy_exec_peak: Vec<i32>, datestamp: Vec<String>, jobs: Vec<i32>, minutes: Vec<i32>) -> Activity {
        Activity {
            ccy_exec_peak,
            datestamp,
            jobs,
            minutes,
        }
    }
}


