/*
 * Sauce Labs REST API
 *
 * This is a REST API documentation provided by Sauce Labs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@saucelabs.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CiStat {
    /// CI platform which is being used
    #[serde(rename = "platform")]
    pub platform: String,
    /// platform version
    #[serde(rename = "platform_version", skip_serializing_if = "Option::is_none")]
    pub platform_version: Option<String>,
}

impl CiStat {
    pub fn new(platform: String) -> CiStat {
        CiStat {
            platform,
            platform_version: None,
        }
    }
}


