/*
 * Sauce Labs REST API
 *
 * This is a REST API documentation provided by Sauce Labs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@saucelabs.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Concurrency {
    #[serde(rename = "concurrency")]
    pub concurrency: ::std::collections::HashMap<String, crate::models::OrgTeamConcurrencyValues>,
    #[serde(rename = "timestamp")]
    pub timestamp: f32,
}

impl Concurrency {
    pub fn new(concurrency: ::std::collections::HashMap<String, crate::models::OrgTeamConcurrencyValues>, timestamp: f32) -> Concurrency {
        Concurrency {
            concurrency,
            timestamp,
        }
    }
}


