/*
 * Sauce Labs REST API
 *
 * This is a REST API documentation provided by Sauce Labs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@saucelabs.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConcurrencyLimit {
    /// Number of concurrent mac VMs allowed
    #[serde(rename = "mac", skip_serializing_if = "Option::is_none")]
    pub mac: Option<i32>,
    #[serde(rename = "overall", skip_serializing_if = "Option::is_none")]
    pub overall: Option<i32>,
    #[serde(rename = "real_device", skip_serializing_if = "Option::is_none")]
    pub real_device: Option<i32>,
    #[serde(rename = "scout", skip_serializing_if = "Option::is_none")]
    pub scout: Option<i32>,
}

impl ConcurrencyLimit {
    pub fn new() -> ConcurrencyLimit {
        ConcurrencyLimit {
            mac: None,
            overall: None,
            real_device: None,
            scout: None,
        }
    }
}


