/*
 * Sauce Labs REST API
 *
 * This is a REST API documentation provided by Sauce Labs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@saucelabs.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct File {
    #[serde(rename = "md5")]
    pub md5: String,
    #[serde(rename = "mtime")]
    pub mtime: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "size")]
    pub size: i32,
}

impl File {
    pub fn new(md5: String, mtime: String, name: String, size: i32) -> File {
        File {
            md5,
            mtime,
            name,
            size,
        }
    }
}


