/*
 * Sauce Labs REST API
 *
 * This is a REST API documentation provided by Sauce Labs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@saucelabs.com
 * Generated by: https://openapi-generator.tech
 */

/// InlineResponse2003 : desired capabilities of manual job



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2003 {
    /// false if job got created successfully
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<bool>,
    /// id of the job (available when created, otherwise \"null\")
    #[serde(rename = "job_id", skip_serializing_if = "Option::is_none")]
    pub job_id: Option<serde_json::Value>,
    #[serde(rename = "metadata")]
    pub metadata: Box<crate::models::InlineResponse2003Metadata>,
    /// id of the manual task
    #[serde(rename = "task_id")]
    pub task_id: String,
}

impl InlineResponse2003 {
    /// desired capabilities of manual job
    pub fn new(metadata: crate::models::InlineResponse2003Metadata, task_id: String) -> InlineResponse2003 {
        InlineResponse2003 {
            error: None,
            job_id: None,
            metadata: Box::new(metadata),
            task_id,
        }
    }
}


