/*
 * Sauce Labs REST API
 *
 * This is a REST API documentation provided by Sauce Labs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@saucelabs.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2002Response {
    #[serde(rename = "cta", skip_serializing_if = "Option::is_none")]
    pub cta: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl InlineResponse2002Response {
    pub fn new() -> InlineResponse2002Response {
        InlineResponse2002Response {
            cta: None,
            id: None,
            message: None,
        }
    }
}


