/*
 * Sauce Labs REST API
 *
 * This is a REST API documentation provided by Sauce Labs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@saucelabs.com
 * Generated by: https://openapi-generator.tech
 */

/// Platform : Platforms that sauce supports



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Platform {
    #[serde(rename = "api_name", skip_serializing_if = "Option::is_none")]
    pub api_name: Option<String>,
    #[serde(rename = "automation_backend", skip_serializing_if = "Option::is_none")]
    pub automation_backend: Option<String>,
    /// that thing
    #[serde(rename = "deprecated_backend_versions", skip_serializing_if = "Option::is_none")]
    pub deprecated_backend_versions: Option<Vec<String>>,
    #[serde(rename = "device", skip_serializing_if = "Option::is_none")]
    pub device: Option<String>,
    #[serde(rename = "latest_stable_version", skip_serializing_if = "Option::is_none")]
    pub latest_stable_version: Option<String>,
    #[serde(rename = "long_name", skip_serializing_if = "Option::is_none")]
    pub long_name: Option<String>,
    /// Image URL representing the product.
    #[serde(rename = "long_version", skip_serializing_if = "Option::is_none")]
    pub long_version: Option<String>,
    #[serde(rename = "os", skip_serializing_if = "Option::is_none")]
    pub os: Option<String>,
    #[serde(rename = "recommended_backend_version", skip_serializing_if = "Option::is_none")]
    pub recommended_backend_version: Option<String>,
    /// Image URL representing the product.
    #[serde(rename = "short_version", skip_serializing_if = "Option::is_none")]
    pub short_version: Option<String>,
    #[serde(rename = "supported_backend_versions", skip_serializing_if = "Option::is_none")]
    pub supported_backend_versions: Option<Vec<String>>,
}

impl Platform {
    /// Platforms that sauce supports
    pub fn new() -> Platform {
        Platform {
            api_name: None,
            automation_backend: None,
            deprecated_backend_versions: None,
            device: None,
            latest_stable_version: None,
            long_name: None,
            long_version: None,
            os: None,
            recommended_backend_version: None,
            short_version: None,
            supported_backend_versions: None,
        }
    }
}


